### ISSUE TITLE
could not open ASY file

### ISSUE THREAD

**Issue by greengrocer98** [ckuhlmann/lt2circuitikz#1]
You 've made great job. Your script works nicely with standart elements like "R", "C", but if i try to use elements from circuitikz library python script can't read ASY file. I 've tried to solve this problem by myself, but... 
![image](https://user-images.githubusercontent.com/36965345/48797514-6fc2d080-ed13-11e8-82cb-68aa0747fe4d.png) this is screenshot of my error. Do you know what's the problem?

**Comment by greengrocer98** [comment]
I'm so sorry. Perhaps i did somethinf wrong in requarements. It's necessary to replace all ASY files.

**Comment by ckuhlmann** [comment]
Hi,
thanks for the kind words and sorry to hear that the script gives you troubles.
I think the problem is that the script tries to load the symbols for circuiTikz relative to the current working directory, which it assumes to be the current script dir. However, your console working directory is not the script directory, so it fails.

You should be able to circumvent this bug by starting the script from the directory where you extracted it to, like so:
`cd "C:\stuff\myapp\lt2circuitikz-master\lt2circuitikz-master\"`
then, run it in the same console window via
`python "C:\stuff\myapp\lt2circuitikz-master\lt2circuitikz-master\lt2ti.py" "C:\stuff\myapp\lt2circuitikz-master\lt2circuitikz-master\Draft1.asc"`
Please note that the command above is only one line, although it gets wraped here.

Could you please try to process your file again using these commands?

I will update the script to be a bit smarter about this and will add a note to the documentation. Unfortunately, it may take me a few days since I'm busy with other stuff during the week. In the meantime, you can use a batch file to automate the steps above, so you don't have to type that over and over again.

Cheers.

**Comment by greengrocer98** [comment]
Yeah, I solved this problem. There are 2 solutions: the first is your's. It's possible to run the script from the following directory, The second: it's possible to copy all the files from master to sym in LTspice. All files will have the same names and script will work right. It would be also nice to add a small documentation how to create a new symbol. For a example there is no any switches. If you could do this I will help you to create all other circuitikz elememnts. Now i'm trying to create normal open switch(nos), but i'm doing it very slowly yet.

**Comment by ckuhlmann** [comment]
Hi,
for symbol creation, take a look at the list of tokens in the _*.asy2tex file documentation_ section of the readme. The asy2tex file latex section (between BeginTex / EndTex) is essentially what gets written to the tex document. Elements between hash symbols # are keywords that get replaced by data from the asc file, e.g. position and element names.
Best way to learn this might be to look at the existing asy2tex files. I will try to write a more detailed documentation on how to do this, but don't hold your breath.

While I haven't looked deeper into the problem with the path yet, I have added your nos switch: 61df04c628f1cac4fe849d4a5e3da93f654b2b40 . You should have no problems creating the other switches from it by copying and modifying the asy and asy2tex file. Have fun.
As of 270c6a4e276deb2253d82d1faed51ed6199ec22e, there is a very basic tutorial in the readme on the steps required to add new symbols. I hope it helps to get you started.

**Comment by ckuhlmann** [comment]
Do you still have the Draft1.asc file that gave you an error? If so, could you please attach it here? 

I suspect that you had copied the sym32a folder to the LTspice lib directory, instead of its contents. When you then inserted the cap_t symbol, its relative path in the spice library (that gets written to the asc) did not match the relative path in the sym32a folder, hence the error.

I have improved the section in the readme that deals with copying the symbols, so this is clearer. The instructions were a bit ambiguous whether sym32a should be copied as well.

**Comment by greengrocer98** [comment]
Exactly so. The first time when I use your script, I copied sym32a folder, not files. I got that it cause error. It’s necessary to copy files, not folder.
