### ISSUE TITLE
Problems with circuit elements

### ISSUE THREAD

**Issue by PuyGonzalo** [ckuhlmann/lt2circuitikz#2]
Hi, I know this is kind of old but let me tell you, you've done a magnificent work!
The script works like a charm! The only thing is, i can't find out how to change the default ground or the default style of the circuit elements (american/European). 
I managed to change the style to American but only when i open the .tex file and edit it myself, Is there a way to include this style automatically when the script run?
The other thing I couldn't find a way to change is the default ground (rground), I've tried to manually change all 'rground' to 'ground' (the one i like) but it puts it rotated to the right.

Btw, the script is amazing, congratulations for you work!

**Comment by ckuhlmann** [comment]
Hi gongus,
I'm really glad you like the script and find it helpful.

1. To configure the default GND, there is now an ini switch `default_gnd=circuiTikz\ground` that is available in the `sym32a\sym.ini` to define the default asy2tex file to use for node 0. Please also see the updated readme.md
2. To configure american symbol styles, just edit the preamble `sym32a\latex_preamble.tex` as you see fit, or copy the sym32a folder e.g. to sym32a_us and point to that one in the `lt2ti.ini` under `[general]` by setting `symdir=sym32a_us`. This allows you to switch styles/settings by changing only one ini line.

Please let me know if there are other (hard coded) dead ends you run into while trying to achieve the result you want. Though I can't promise any extensive changes, I will do my best to make the script more customizable.

If you create support for additional circuitikz symbols, I will happily add them to the collection, just do a pull-request.
Thanks for using the script.

**Comment by PuyGonzalo** [comment]
Hi ckuhlmann,
Thank you for answering soon.

The good news is that i correctly modified the `sym32a\latex_preamble.tex` to set the resistors to american.
But the default GND is giving me trouble. I change the `sym.ini` file with the new one, and set the ground thati wanted but with no positive changes, I still get the rground. Later, I also change the `sym.ini` file at the  `LTspiceXVII\lib` hoping this will fix the problem. but nothing happened and I still get the rground. What am i doing wrong ?

Thank you for your help, hope I can fix it soon!

Best wishes

**Comment by ckuhlmann** [comment]
Hi gongus,
sorry it doesn't work for you. However, I've checked again and it works at my end.

Could you please 
1. download a fresh zip of the project and extract it to a new location (no need to change your ltspice lib)
2. extract the [attached gnd-test.zip](https://github.com/ckuhlmann/lt2circuitikz/files/3307128/gnd-test.zip) into the root folder (the one with lt2ti.py) of your new clone,
3. Replace the `sym.ini` in sym32a if asked to (or modify it so it says `default_gnd=circuiTikz\ground` under `[general]`.
4. Run `test_lt2ti_gnd.bat` in the examples folder
5. Run `compile_gnd-test.bat` in the examples folder
6. Check if `gnd-test.asc.pdf` has a ground cross
7. Attach `test_lt2ti-gnd.log` and `gnd-test.asc.tex` from the examples folder if it still does not work?

This setup creates your desired ground symbols for me.

If calling lt2ti.py with your own files, make sure the working directory when calling is the root directory (the directory where lt2ti.py resides). Otherwise, some config files might not be found. See `test_lt2ti_gnd.bat`. I will try to fix this, but don't hold your breath.

Kind regards

**Comment by PuyGonzalo** [comment]
Hello ckuhlmann,

This work great! I don't know what I was doing wrong before, but now it's all fine.
Let me tell you again that this script is incredible and saves me a ton of time.

Best regards.
